trigger:
  batch: true
  branches:
    include:
    - dev

  paths:
    include:
    - /backend-app/backend
    - /backend-app/manifest
    - /backend-app/pipelines-yml

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: common-acr-build.yml

