trigger:
  batch: true
  branches:
    include:
      - production
  paths:
    include:
    - /backend-app/backend
      /backend-app/minifest
      /backend-app/pipelines-yml

pool:
  vmImage: ubuntu-latest

extends:
  template: acr-pipeline.yml