trigger:
  batch: true
  branches:
    include:
    - stageing

  paths:
    include:
    - /backend-app/backend
      /backend-app/minifest
      /backend-app/pipelines-yml

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: common-acr-build.yml

