
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: gs
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      restartPolicy: Always
      containers:
      - name: node
        image: gsvikrant.azurecr.io/node:node
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 10m


---

apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: gs
  annotations:
    service.beta.kubernetes.io/azure-load-balancer: "true"
spec:
  selector:
    app: node
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 5000


--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node
  namespace: gs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
