stages:
- stage: push
  displayName: Deploy-to-acr
  jobs:
    - job: staging
      displayName: creating-image
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/staging')
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'demo-docker-connection'
          repository: 'staging-node'
          command: 'buildAndPush'
          Dockerfile: '**/api-app/api/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(agent.builddirectory)/s/api-app'
          Contents: '**'
          TargetFolder: '$(build.artifactstagingdirectory)/a'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/a'
          ArtifactName: 'drop'
          publishLocation: 'Container'

    - job: dev
      displayName: creating-image
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'demo-docker-connection'
          repository: 'dev-node'
          command: 'buildAndPush'
          Dockerfile: '**/api-app/api/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(agent.builddirectory)/s/api-app'
          Contents: '**'
          TargetFolder: '$(build.artifactstagingdirectory)/a'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/a'
          ArtifactName: 'drop'
          publishLocation: 'Container'  
        
      
    - job: production
      displayName: creating-image
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/production')
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(agent.builddirectory)/s/api-app'
          Contents: '**'
          TargetFolder: '$(build.artifactstagingdirectory)/a'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/a'
          ArtifactName: 'drop'
          publishLocation: 'Container'  