trigger:
  batch: true
  branches:
    include:
      - production
  paths:
    include:
    - /api-app/api
    - /api-app/manifest
    - /api-app/pipelines-yml

pool:
  vmImage: ubuntu-latest

extends:
  template: acr-pipeline.yml